export {
  extractEnvNames,
  findHostShadowDeps,
  classifyScriptHazards,
  lifecycleScriptTargets,
  classifyLifecycleHazards,
  parseLockfileVersions,
  readVulnScanDeps,
  filterVulnerabilityHits,
  isSecretScanFile,
  isSecretScanSkipDir,
  ENV_PATTERN,
  HOST_SHADOW_PACKAGES,
  HAZARD_CRED_PATTERNS,
  SCRIPT_HAZARD_PATTERNS,
  HAZARD_ALLOWLIST_DOMAINS,
  HAZARD_COMBO_PATTERNS,
  JS_HAZARD_PATTERNS,
  SECRET_SCAN_EXTENSIONS,
  SECRET_SCAN_BASENAMES,
  SECRET_SCAN_SKIP_DIRS,
  SECRET_SCAN_MAX_FILES,
  SECRET_SCAN_MAX_FILE_BYTES,
  CVE_MAX_QUERIES,
} from "./security-scan.js";
